# Generated by Django 4.1 on 2024-08-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_audiofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='file_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
