# Generated by Django 4.1 on 2024-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_album_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='file_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
